### ISSUE TITLE
Call to llvm-cxxfilt fails

### ISSUE THREAD

**Issue by WillTrojak** [AMDResearch/omniperf#165]
**Describe the bug**
When running omniperf after profiling the application, omniperf attempts to run llvm-cxxfilt, however, this line fails. In a recent commit this line was added 
https://github.com/AMDResearch/omniperf/blob/3affe48cd84fa3302d2bc68fabdee1c331fe38ff/src/utils/csv_processor.py#L60 It has a hard path to /opt/rocm was added for `llvm-cxxfilt`, however on Frontier as there are multiple versions of rocm, there is no /opt/rocm directory. 

**Development Environment:**
 - Linux Distribution: SLES 15.4
 - Omniperf Version: 1.0.9 (release)
 - GPU: Mi250x
 - Custer (if applicable): Frontier

**To Reproduce**
Profile any application on a system that does not have a `/opt/rocm` directory.

**Expected behavior**
Omniperf should finish successfully.

**Screenshots**
```
...
ROCPRofiler: 1 contexts collected, output directory /tmp/rpl_data_230822_061954_126482/input0_results_230822_061954
File '/lustre/orion/cfd175/proj-shared/tests/workloads/test3/mi200/pmc_perf_0.csv' is generating
/lustre/orion/cfd175/proj-shared/tests/workloads/test3/mi200/perfmon/pmc_perf_1.txt
RPL: on '230822_061955' from '/opt/rocm-5.5.1' in '/lustre/orion/cfd175/proj-shared/tests'
RPL: profiling '""./go""'
RPL: input file '/lustre/orion/cfd175/proj-shared/tests/workloads/test3/mi200/perfmon/pmc_perf_1.txt'
RPL: output dir '/tmp/rpl_data_230822_061955_126679'
RPL: result dir '/tmp/rpl_data_230822_061955_126679/input0_results_230822_061955'
ROCProfiler: input from "/tmp/rpl_data_230822_061955_126679/input0.xml"
  gpu_index = 
  kernel = 
  range = 
  9 metrics
    SQ_INSTS_VALU_ADD_F64, SQ_INSTS_VALU_MUL_F64, SQ_INSTS_VALU_FMA_F64, SQ_INSTS_VALU_TRANS_F64, SQ_INSTS_VALU_MFMA_MOPS_F16, SQ_INSTS_VALU_MFMA_MOPS_BF16, SQ_INSTS_VALU_MFMA_MOPS_F32, SQ_INSTS_VALU_MFMA_MOPS_F64, TCP_TCC_ATOMIC_WITHOUT_RET_REQ_sum
 System minor 0
 System major 9
 agent prop name 
hip Device prop succeeded 
PASSED!

ROCPRofiler: 1 contexts collected, output directory /tmp/rpl_data_230822_061955_126679/input0_results_230822_061955
File '/lustre/orion/cfd175/proj-shared/tests/workloads/test3/mi200/pmc_perf_1.csv' is generating
Traceback (most recent call last):
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/omniperf", line 909, in <module>
    main()
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/omniperf", line 783, in main
    roof_setup(args, my_parser, VER)
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/omniperf", line 308, in roof_setup
    characterize_app(args, VER)
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/omniperf", line 448, in characterize_app
    csv_processor.kernel_name_shortener(workload_dir, args.kernelVerbose)
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/utils/csv_processor.py", line 135, in kernel_name_shortener
    modified_df = shorten_file(orig_df, level)
  File "/lustre/orion/cfd175/proj-shared/pyfr_prof_venv/bin/utils/csv_processor.py", line 62, in shorten_file
    proc = subprocess.Popen(
  File "/opt/cray/pe/python/3.10.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/cray/pe/python/3.10.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocm/llvm/bin/llvm-cxxfilt'
```

**Comment by coleramos425** [comment]
Fixed in `main`.

https://github.com/AMDResearch/omniperf/commit/7187218ed94eb1ce72e77ed7139ca46157210985

**Comment by coleramos425** [comment]
@WillTrojak please try again with the latest `v1.0.10` module which I have loaded on your system. The issue should be fixed.
